import type { Metadata } from 'next'

import './globals.css'
import Navbar from '@/components/Navbar'

export const metadata: Metadata = {
  title: 'e-commerce-nextjs',
  description: 'Generated by appncy',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="container m-auto grid min-h-screen grid-rows-[auto,1fr,auto]">
        <Navbar />
        <main className="py-8">{children}</main>
        <footer className="text-center leading-[3rem] opacity-70">
          © {new Date().getFullYear()} e-commerce-nextjs
        </footer>
      </body>
    </html>
  )
}
